version: '3.8'

services:
  jdownloader:
    build:
      context: .
      dockerfile: Dockerfile
    image: jd2captchasolver:latest
    container_name: jdownloader2
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=Etc/UTC
      # Set to 'true' if you want detailed image transform logs in /config/tools/offlineCaptchaSolver/log.txt
      - DEBUG=false
    ports:
      - "5800:5800" # JDownloader 2 Web GUI
    volumes:
      # Persistent configuration and download folders
      - ./config:/config
      - ./downloads:/output
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
